fragment PagesParts on Pages {
  __typename
  title
  seoDescription
  ogImage
  translationSlug
  blocks {
    __typename
    ... on PagesBlocksHeroBlock {
      headline
      variant
      subheadline
      backgroundImage
      ctaLabel
      ctaUrl
    }
    ... on PagesBlocksContentBlock {
      body
    }
    ... on PagesBlocksBookingBlock {
      enabled
      bookingUrl
      label
    }
    ... on PagesBlocksFeatureGridBlock {
      items {
        __typename
        icon
        title
        description
      }
    }
    ... on PagesBlocksFullBleedBlock {
      image
      altText
      minHeight
      overlayOpacity
      headline
      subtext
    }
    ... on PagesBlocksInteractiveListBlock {
      title
      items {
        __typename
        label
        description
        image
        imageAlt
      }
    }
    ... on PagesBlocksFaqBlock {
      title
      questions {
        __typename
        question
        answer
      }
    }
  }
}
