fragment PagesParts on Pages {
  __typename
  title
  seoDescription
  ogImage
  translationSlug
  blocks {
    __typename
    ... on PagesBlocksHeroBlock {
      name
      headline
      variant
      subheadline
      subBodyText
      backgroundImage
      logoOverlay
      ctaLabel
      ctaUrl
    }
    ... on PagesBlocksContentBlock {
      name
      body
      fullBleed
      backgroundImage
    }
    ... on PagesBlocksBookingBlock {
      name
      enabled
      bookingUrl
      label
    }
    ... on PagesBlocksFeatureGridBlock {
      name
      items {
        __typename
        icon
        title
        description
      }
    }
    ... on PagesBlocksFullBleedBlock {
      name
      image
      altText
      minHeight
      overlayOpacity
      headline
      subtext
    }
    ... on PagesBlocksInteractiveListBlock {
      name
      title
      items {
        __typename
        label
        description
        image
        imageAlt
      }
    }
    ... on PagesBlocksFaqBlock {
      name
      title
      questions {
        __typename
        question
        answer
      }
    }
    ... on PagesBlocksBsportCalendar {
      name
      elementId
    }
    ... on PagesBlocksBsportPasses {
      name
      elementId
    }
    ... on PagesBlocksBsportSubscription {
      name
      elementId
    }
  }
}
