services:
  eosclub-astro:
    image: node:20-alpine
    container_name: eosclub_astro
    restart: unless-stopped
    command: tail -f /dev/null
    volumes:
      - /var/www/public/eos.khanyi.com:/app/repo
      - /var/www/public/eos.khanyi.com/dist:/app/dist
    env_file:
      - /var/www/private/eosclub/.env
    networks:
      - backend
    logging:
      driver: journald
      options:
        tag: "eosclub-astro"
        mode: non-blocking
        max-buffer-size: "4m"

networks:
  backend:
    name: docker_backend
    external: true
